# Generated by Django 3.2.3 on 2021-05-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_book_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-added_date']},
        ),
        migrations.AddField(
            model_name='book',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
