# Generated by Django 3.2.3 on 2021-05-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_auto_20210517_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='about',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='about',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
