# Generated by Django 3.2.3 on 2021-05-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_auto_20210517_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
