# Generated by Django 3.2.3 on 2021-05-17 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_author_added_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['-added_date']},
        ),
    ]
