# Generated by Django 3.2.3 on 2021-05-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0007_bookcomments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcomments',
            options={'ordering': ['-date']},
        ),
    ]
